### ISSUE TITLE
Failure at end of step 2 (optimize scrapy parameters)

### ISSUE THREAD

**Issue by justinccdev** [buzzbangorg/bsbang-crawler-ng#13]
At the end of step 2, I see the following failure

```
2018-06-26 15:25:09 [mongodb] INFO: Sample added to MongoDB database!
2018-06-26 15:25:10 [sitemap] INFO: Crawled - 200 - https://www.ebi.ac.uk/biosamples/sitemap/572
2018-06-26 15:25:10 [sitemap] INFO: Crawling 6 of 573 pages
2018-06-26 15:25:13 [statcol] INFO: 203 documents present in the DB after crawl
2018-06-26 15:25:13 [statcol] INFO: closed spider sitemap
2018-06-26 15:25:13 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method StatsCollector.spider_closed of <bioschemas_scraper.extensions.StatsCollector object at 0x7f2e9db56940>>
Traceback (most recent call last):
  File "/home/justincc/.local/lib/python3.6/site-packages/twisted/internet/task.py", line 517, in _oneWorkUnit
    result = next(self._iterator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justincc/.local/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/justincc/.local/lib/python3.6/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/justincc/jc/knowledge/natural/bio/data/search/engines/buzzbang/crawler/src/bsbang-crawler-ng/bioschemas_scraper/bioschemas_scraper/extensions.py", line 60, in spider_closed
    generate_report(final_stats)
  File "/home/justincc/jc/knowledge/natural/bio/data/search/engines/buzzbang/crawler/src/bsbang-crawler-ng/bioschemas_scraper/bioschemas_scraper/custom.py", line 77, in generate_report
    df.to_csv(filepath)
  File "/home/justincc/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 1745, in to_csv
    formatter.save()
  File "/home/justincc/.local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 165, in save
    compression=self.compression)
  File "/home/justincc/.local/lib/python3.6/site-packages/pandas/io/common.py", line 400, in _get_handle
    f = open(path_or_buf, mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: '../log/scrapy_stats.csv'
2018-06-26 15:25:13 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 108514,
 'downloader/request_count': 422,
 'downloader/request_method_count/GET': 422,
 'downloader/response_bytes': 1576913,
 'downloader/response_count': 422,
 'downloader/response_status_count/200': 211,
 'downloader/response_status_count/301': 211,
 'finish_reason': 'closespider_itemcount',
 'finish_time': datetime.datetime(2018, 6, 26, 14, 25, 12, 949608),
 'item_scraped_count': 203,
 'log_count/ERROR': 1,
 'log_count/INFO': 1079,
 'memdebug/gc_garbage_count': 0,
 'memdebug/live_refs/BiosamplesSitemapSpider': 1,
 'memdebug/live_refs/Request': 56874,
 'memusage/max': 100823040,
 'memusage/startup': 100823040,
 'request_depth_max': 2,
 'response_received_count': 211,
 'scheduler/dequeued': 421,
 'scheduler/dequeued/memory': 421,
 'scheduler/enqueued': 57294,
 'scheduler/enqueued/memory': 57294,
 'start_time': datetime.datetime(2018, 6, 26, 14, 24, 46, 576273)}
2018-06-26 15:25:13 [scrapy.core.engine] INFO: Spider closed (closespider_itemcount)
```

**Comment by justinccdev** [comment]
Creating the `../log` directory manually fixes it.

**Comment by innovationchef** [comment]
I forgot to commit the log folder. Now done.
